### ISSUE TITLE
Typo#1 in 01-introduction-tabular-data

### ISSUE THREAD

**Issue by lmterryn** [jorisvandenbossche/DS-python-geospatial#18]
There is a typo in the table "An overview of the possible comparison operations" 
It should be:

An overview of the possible comparison operations:

Operator   |  Description
------ | --------
==       | Equal
!=       | Not equal
\>       | Greater than
\>=       | Greater than or equal
<       | Lesser than
!>       | Lesser than or equal

and to combine multiple conditions:

Operator   |  Description
------ | --------
&       | And (`cond1 & cond2`)
\|       | Or (`cond1 \| cond2`)

**Comment by stijnvanhoey** [comment]
Thanks for reporting.
