### ISSUE TITLE
Feedback xarray intro

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-geospatial#28]
- Better explain DataArray vs DataSet:
  - Probably we can just start with explaining DataArray first (and do exercises on it), and only later Dataset
  - The raster satellite image might be less suited to explain the Dataset, we can better take an example where its clearer that there are multile variables (like temperature and pressure, ..)

- Only explain "there can be more coordinates as dimensions" later on (eg when it actually occurs in the data of the exercises)

- Be consistent with `.values` vs `.data`

- (for pandas -> also use the `.plot.<type>()` pattern instead of `.plot(kind=<type>)` for consistency)

- mistake in exercise: use salinity instead of pressure to calculate the buoyancy

- only explain conversion of dataarray <-> dataset when both concepts are already known (and then can show benefit of either way)

**Comment by stijnvanhoey** [comment]
These elements are now tackled, closing this one.
