### ISSUE TITLE
Feedback numpy notebook

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-geospatial#36]
* Do we need `squeeze()` ?
  * Or can we use indexing as well?
  * If we use it for numpy, should maybe use it for geopandas as well? (instead of `.item()`)
* Leave `where` for the "extra" section at the bottom
* Add some more visual illustrations (see new numpy docs)

**Comment by stijnvanhoey** [comment]
closing, as no longer real content
